server.port: 7001

spring.datasource:
    url: jdbc:mysql://10.89.100.16:8092/data_center?autoReconnect=true&useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: 125!@#09Qsc
    driver-class-name: com.mysql.jdbc.Driver