### server settings
server:
  port: 8099
  servlet:
    context-path: /fun-api
    session:
      timeout: 600

management:
  endpoints:
    web:
      base-path: /fun-manage
      exposure.include: health
  health:
      elasticsearch.enabled: false
      redis.enabled: false
  endpoint:
    health.show-details: always

spring:
  profiles:
    active: dev

#spring.messages:
#  basename: i18n/messages
#  encoding: utf-8
#  # cache-seconds: 300
#  fallbackToSystemLocale: false

spring.datasource:
  type: com.zaxxer.hikari.HikariDataSource
  hikari:
    minimum-idle: 5
    maximum-pool-size: 50
    auto-commit: true
    idle-timeout: 60000
    pool-name: hikariCP
    max-lifetime: 1800000
    connection-timeout: 30000
    connection-test-query: SELECT 1

mybatis-plus:
    ## 分隔符 ",; \t\n"
    type-aliases-package: com.didichuxing.dps.demo.service.dao.domain;com.didichuxing.dps.demo.service.dao.query
    configuration:
        map-underscore-to-camel-case: true
        default-fetch-size: 100
        default-statement-timeout: 30
    mapperLocations:
      - classpath*:spring/mybatis/mapping/**/*.xml
    global-config:
          db-config:
            ## 主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
            id-type: 0